###
# app configuration
# http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/environment.html
###

common:
  '[app:main]':
    use: egg:hpz
    disable_stack_trace: false
    hpz.PATH: /usr/local/bin
    batch.user.session.timeout: 300000
    pyramid:
      reload_templates: true
      debug_all: false
      debug_authorization: false
      debug_notfound: false
      debug_routematch: false
      default_locale_name: en

    # Authentication
    auth:
      state:
        secret: long_secret_for_redirects1111234
      policy:
        secret: edware_secret
        cookie_name: edware
        hashalg: sha512
        http_only: true
        # Represents the lifetime of the cookie itself, if it's not set, it's session based cookie
        #max_age: 2400
        # Maximum number of seconds which a newly issued ticket will be considered valid
        timeout: 1200
        # Session expiration time
      session:
        timeout: 1200
      idp:
        metadata: ../../resource/idp_metadata.xml
      skip.verify: False
      saml:
        identity_parser: smarter_common.security.sbac_identity_parser.SbacIdentityParser
    cache:
      expire: 3600
      lock_dir: /tmp/memcache
      public:
        data:
            expire: 10
        filtered_data:
            expire: 15552000
        shortlived:
            expire: 7776000
      regions: public.data, public.filtered_data, public.shortlived, session
      session:
        expire: 1200
      type:
       memory
    ldap:
      base:
        dn: ou=environment,dc=edwdc,dc=net

  '[server:main]':
    use: 'egg:waitress#main'
    host: 0.0.0.0
    port: 6544

  ###
  # logging configuration
  # http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/logging.html
  ###

  '[loggers]':
    keys: root, hpz
  '[handlers]':
    keys: console, filelog

  '[formatters]':
    keys: generic

  '[logger_root]':
    level: INFO
    handlers: filelog, console

  '[logger_hpz]':
    level: INFO
    handlers: filelog
    qualname: hpz

  '[handler_console]':
    class: StreamHandler
    args: (sys.stderr,)
    level: NOTSET
    formatter: generic

  '[handler_filelog]':
    class: logging.handlers.TimedRotatingFileHandler
    args: '(''/tmp/hpz.log'',''midnight'')'  # (path, when)
    level: INFO
    formatter: generic

  '[formatter_generic]':
    format: '%(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s'

# End logging configuration


development:
  '[app:main]':
    hpz:
      db:
        schema_name: hpz
        url: postgresql+psycopg2://hpz:hpz2014@localhost:5432/hpz
        pool_size: 5
      frs:
        upload_base_path: /opt/edware/hpz/uploads
        file_size_limit: 4294967296
        download_base_url: http://localhost/download
    auth:
      saml:
        idp_server_login_url: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso/SSORedirect/metaAlias/idp
        idp_server_logout_url: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso/IDPSloRedirect/metaAlias/idp
        issuer_name: http://localhost:80/sp.xml
        name_qualifier: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso

jenkins_dev:
  '[app:main]':
    hpz:
      db:
        schema_name: hpz
        url: postgresql+psycopg2://hpz:hpz2014@localhost:5432/hpz
        pool_size: 5
      frs:
        upload_base_path: /opt/edware/hpz/uploads
        file_size_limit: 4294967296
        download_base_url: http://edwappsrv1.poc.dum.edwdc.net:81/download
    auth:
        saml:
          idp_server_login_url: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso/SSORedirect/metaAlias/idp
          idp_server_logout_url: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso/IDPSloRedirect/metaAlias/idp
          name_qualifier: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso
          issuer_name: 'http://edwappsrv1.poc.dum.edwdc.net:81'

qa:
  '[app:main]':
    hpz:
      db:
        schema_name: hpz
        url: postgresql+psycopg2://hpz:hpz2014@dbpghpz0.qa.dum.edwdc.net:5432/hpz
        pool_size: 5
      frs:
        upload_base_path: /opt/edware/hpz/uploads
        file_size_limit: 4294967296
        download_base_url: http://hpzweb0.qa.dum.edwdc.net/download
    auth:
        idp:
          metadata: /opt/edware/conf/idp_metadata.xml
        saml:
          issuer_name: https://hpzweb0.qa.dum.edwdc.net
          idp_server_login_url: https://auth1.qa.dum.edwdc.net/openam/SSORedirect/metaAlias/idp
          idp_server_logout_url: https://auth1.qa.dum.edwdc.net/openam/IDPSloRedirect/metaAlias/idp
          name_qualifier: https://auth1.qa.dum.edwdc.net/openam
