# DataGeneration Config file for landing zone format

lz:
    json:
        path_to_json_mapping: DEFAULT
    csv:
        REALDATA_RECORDS:
            guid_asmt: student_info.asmt_guids
            guid_asmt_location: school.school_id
            name_asmt_location: school.school_name
            grade_asmt: student_info.grade
            name_state: state_population.state_name
            code_state: state_population.state_code
            guid_district: school.district_id
            name_district: school.district_name
            guid_school: school.school_id
            name_school: school.school_name
            type_school: school.school_category
            guid_student: student_info.student_id
            name_student_first: student_info.first_name
            name_student_middle: student_info.middle_name
            name_student_last: student_info.last_name
            address_student_line1: student_info.address_1
            address_student_line2: student_info.address_2
            address_student_city: student_info.city
            address_student_zip: student_info.zip_code
            gender_student: student_info.gender
            email_student: student_info.email
            dob_student: student_info.dob
            grade_enrolled: student_info.grade
            date_assessed: student_info.asmt_dates_taken
            score_asmt: asmt_score.overall_score
            score_asmt_min: asmt_score.interval_min
            score_asmt_max: asmt_score.interval_max
            score_perf_level: asmt_score.perf_lvl
            score_claim_1: claim_scores.1.claim_score
            score_claim_1_min: claim_scores.1.claim_score_interval_minimum
            score_claim_1_max: claim_scores.1.claim_score_interval_maximum
            asmt_claim_1_perf_lvl: claim_scores.1.perf_lvl
            score_claim_2: claim_scores.2.claim_score
            score_claim_2_min: claim_scores.2.claim_score_interval_minimum
            score_claim_2_max: claim_scores.2.claim_score_interval_maximum
            asmt_claim_2_perf_lvl: claim_scores.2.perf_lvl
            score_claim_3: claim_scores.3.claim_score
            score_claim_3_min: claim_scores.3.claim_score_interval_minimum
            score_claim_3_max: claim_scores.3.claim_score_interval_maximum
            asmt_claim_3_perf_lvl: claim_scores.3.perf_lvl
            score_claim_4: claim_scores.4.claim_score
            score_claim_4_min: claim_scores.4.claim_score_interval_minimum
            score_claim_4_max: claim_scores.4.claim_score_interval_maximum
            asmt_claim_4_perf_lvl: claim_scores.4.perf_lvl
            dmg_eth_hsp: student_info.dmg_eth_hsp
            dmg_eth_ami: student_info.dmg_eth_ami
            dmg_eth_asn: student_info.dmg_eth_asn
            dmg_eth_blk: student_info.dmg_eth_blk
            dmg_eth_pcf: student_info.dmg_eth_pcf
            dmg_eth_wht: student_info.dmg_eth_wht
            dmg_prg_iep: student_info.dmg_prg_iep
            dmg_prg_lep: student_info.dmg_prg_lep
            dmg_prg_504: student_info.dmg_prg_504
            dmg_prg_tt1: student_info.dmg_prg_tt1
            asmt_type: student_info.asmt_types
            asmt_year: student_info.asmt_years
            asmt_subject: student_info.asmt_subjects
