###
# app configuration
# http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/environment.html
###

common:
  '[app:main]': 
    use: egg:smarter
    disable_stack_trace: false
    smarter.PATH: /usr/local/bin
    pyramid:
      reload_templates: true
      debug_all: false
      debug_authorization: false
      debug_notfound: false
      debug_routematch: false
      default_locale_name: en
      includes: pyramid_tm pyramid_exclog pyramid_beaker

    # pyramid_beaker configuration
    cache:
      regions: public.data, session
      type: ext:memcached
      expire: 31556940 # year
      public.data.expire: 31556940 # year
      session.expire: 1200 # 20 minutes
      lock_dir: /tmp/memcache
    
    # Database
    edware:
      db:
        echo: False
    cleanup:
      schedule:
        cron:
          # everyday
          day: '*/1'

    # Authentication
    auth:
      state:
        secret: long_secret_for_redirects1111234
      policy:
        secret: edware_secret
        cookie_name: edware
        hashalg: sha512
        # Represents the lifetime of the cookie itself, if it's not set, it's session based cookie
        #max_age: 2400
        # Maximum number of seconds which a newly issued ticket will be considered valid
        timeout: 1200
        # Session expiration time 
      session:
        timeout: 1200
      idp:
        metadata: ../../resource/idp_metadata.xml

    # Static cache max age
    smarter.resources.static.max_age: 3600
    # We support dev, prod, and test (env that runs FT) modes
    mode: dev
    # Run npm update (dev mode only)
    run.npm.update: true
    # Timeout for pdf generation process
    pdf:
      generate.timeout: 10
      report_base_dir: /tmp/pdf
      celery_timeout: 30
      # Don't regenerate if pdf is in file system
      always.generate: False
    # Used for tenancy
    ldap.base.dn: ou=environment,dc=edwdc,dc=net

  '[server:main]':
    use: 'egg:waitress#main'
    host: 0.0.0.0
    port: 6543
    
  ###
  # logging configuration
  # http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/logging.html
  ###

  '[loggers]':
    keys: root, smarter, sqlalchemy, exc_logger, audit, edauth, security_event

  '[handlers]':
    keys: console, filelog, audit, security_event

  '[formatters]':
    keys: generic, json
    
  '[logger_edauth]':
    level: DEBUG
    handlers: filelog
    qualname: edauth

  '[logger_root]':
    level: INFO
    handlers: filelog, console

  '[logger_smarter]':
    level: INFO
    handlers: filelog
    qualname: smarter

  '[logger_sqlalchemy]':
    level: WARN
    handlers: filelog
    qualname: sqlalchemy
    # "level = INFO" logs SQL queries.
    # "level = DEBUG" logs SQL queries and results.
    # "level = WARN" logs neither.  (Recommended for production systems.)

  '[logger_exc_logger]':
    level: ERROR
    handlers: filelog
    qualname: exc_logger

  '[logger_audit]':
    level: INFO
    handlers: audit
    qualname: audit
    # Important: this means it doesn't propagate to root logger
    propagate: 0
    
  '[logger_security_event]':
    level: INFO
    handlers: security_event
    qualname: security_event
    # Important: this means it doesn't propagate to root logger
    propagate: 0

  '[handler_console]':
    class: StreamHandler
    args: (sys.stderr,)
    level: NOTSET
    formatter: generic
    
  '[handler_filelog]':
    class: logging.handlers.TimedRotatingFileHandler
    args: '(''/tmp/smarter.log'',''midnight'')'  # (path, when) 
    level: INFO
    formatter: generic

  '[handler_audit]':
    class: logging.handlers.TimedRotatingFileHandler
    args: '(''/tmp/audit.log'',''midnight'')'   # (path, when) 
    level: INFO
    formatter: json
    
  '[handler_security_event]':
    class: logging.handlers.TimedRotatingFileHandler
    args: '(''/tmp/security_event.log'',''midnight'')'   # (path, when) 
    level: INFO
    formatter: json

  '[formatter_generic]':
    format: '%(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s'

  '[formatter_json]':
    class: edapi.logging.JsonDictLoggingFormatter
    format: '%(asctime)s %(message)s'


# End logging configuration

qa1:
  '[app:main]':
    mode: prod
    edware:
      db:
        schema_name: edware_sds_0_1
        cat.url: postgresql+psycopg2://edware:edware2013@dwpool0.qa.dum.edwdc.net:6432/edware
    auth:
      idp:
        metadata: /opt/edware/conf/idp_metadata.xml
      policy:
        secure: true
      skip.verify: False
      saml:
        issuer_name: https://ha-int-pyweb1.qa.dum.edwdc.net
        idp_server_login_url: https://auth0.qa.dum.edwdc.net/openam/SSORedirect/metaAlias/idp
        idp_server_logout_url: https://auth0.qa.dum.edwdc.net/openam/IDPSloRedirect/metaAlias/idp
        name_qualifier: https://auth0.qa.dum.edwdc.net/openam
  '[handlers]':
    keys: console, filelog, audit, syslog
  '[handler_syslog]':
    class: logging.handlers.SysLogHandler
    args: '(''/dev/log'', handlers.SysLogHandler.LOG_LOCAL1)'
    level: WARN
    formatter: generic
  '[logger_smarter]':
    level: WARN
    handlers: syslog
    qualname: smarter
  '[logger_edauth]':
    level: WARN
    handlers: syslog
    qualname: edauth

qa2:
  '[app:main]':
    mode: prod
    edware:
      db:
        schema_name: edware_delaware_0_1
        cat:
          url: postgresql+psycopg2://edware:edware2013@dwpool0.qa.dum.edwdc.net:6434/edware
    auth:
      idp:
        metadata: /opt/edware/conf/idp_metadata.xml
      policy:
        secure: true
      skip.verify: False
      saml:
        issuer_name: https://ha-int-pyweb2.qa.dum.edwdc.net
        idp_server_login_url: https://auth0.qa.dum.edwdc.net/openam/SSORedirect/metaAlias/idp
        idp_server_logout_url: https://auth0.qa.dum.edwdc.net/openam/IDPSloRedirect/metaAlias/idp
        name_qualifier: https://auth0.qa.dum.edwdc.net/openam
  '[handlers]':
    keys: console, filelog, audit, syslog
  '[handler_syslog]':
    class: logging.handlers.SysLogHandler
    args: '(''/dev/log'', handlers.SysLogHandler.LOG_LOCAL1)'
    level: WARN
    formatter: generic
  '[logger_smarter]':
    level: WARN
    handlers: syslog
    qualname: smarter
  '[logger_edauth]':
    level: WARN
    handlers: syslog
    qualname: edauth

jenkins_qa:
  '[app:main]':
    mode: test
    edware:
      db:
        schema_name: edware_sds_0_1
        cat:
          url: postgresql+psycopg2://postgres:edware.qa.2013@dwpool0.qa.dum.edwdc.net:6432/edware

uat:
  '[app:main]':
    mode: prod
    pdf.report_base_dir: /opt/edware/pdf
    disable_stack_trace: true
    edware:
      db:
        schema_name: edware_uat_0_1
        cat:
          url: postgresql+psycopg2://edware:edware.dmo.may.2013@dwpool0.dmo.som.edwdc.net:6434/edware
    auth:
      idp:
        metadata: /opt/edware/conf/idp_metadata.xml
      policy:
        secure: true
      skip.verify: False
      saml:
        issuer_name: https://pyweb.dmo.som.edwdc.net
        idp_server_login_url: https://betaauth.smarterbalancedreporting.org/openam/SSORedirect/metaAlias/idp
        idp_server_logout_url: https://betaauth.smarterbalancedreporting.org/openam/IDPSloRedirect/metaAlias/idp
        name_qualifier: https://betaauth.smarterbalancedreporting.org/openam
  '[handlers]':
    keys: audit, syslog
  '[logger_root]':
    level: INFO
    handlers: syslog
  '[handler_syslog]':
    class: logging.handlers.SysLogHandler
    args: '(''/dev/log'', handlers.SysLogHandler.LOG_LOCAL1)'
    level: WARN
    formatter: generic
  '[handler_audit]':
    class: logging.handlers.SysLogHandler
    args: '(''/dev/log'', handlers.SysLogHandler.LOG_LOCAL0)'
    level: WARN
    formatter: json
  '[handler_audit]':
    class: logging.handlers.SysLogHandler
    args: '(''/dev/log'', handlers.SysLogHandler.LOG_LOCAL2)'
    level: WARN
    formatter: json
  '[logger_smarter]':
    level: WARN
    handlers: syslog
    qualname: smarter
  '[logger_edauth]':
    level: WARN
    handlers: syslog
    qualname: edauth
  '[logger_sqlalchemy]':
    level: WARN
    handlers: syslog
    qualname: sqlalchemy
  '[logger_exc_logger]':
    level: ERROR
    handlers: syslog
    qualname: exc_logger

localOpenAM:
  '[app:main]':
    edware:
      db:
        schema_name: edware_sds_0_2
        cat:
          url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware
          echo: False
    auth:
      skip.verify: False
      saml:
        idp_server_login_url: http://local.slidev.org:8080/openam/SSORedirect/metaAlias/idp
        idp_server_logout_url: http://local.slidev.org:8080/openam/IDPSloRedirect/metaAlias/idp
        issuer_name: http://local.slidev.org:6543/sp.xml
        name_qualifier: http://local.slidev.org:8080/openam
    mode: dev

development:
  '[app:main]':
    cache:
      regions: public.data, session
      type: memory
      public.data.expire: 10
    # Celery config
    celery:
      celery_always_eager: true
    edware:
      db:
        cat:
          schema_name: edware_sds_0_2
          url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware
          pool_size: 20
          max_overflow: 10
    auth:
      skip.verify: False
      saml:
        idp_server_login_url: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso/SSORedirect/metaAlias/idp
        idp_server_logout_url: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso/IDPSloRedirect/metaAlias/idp
        issuer_name: http://localhost:6543/sp.xml
        name_qualifier: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso
    
    # Don't cache any static contents
    smarter.resources.static.max_age: 0
    # Always generate pdf regardless if it exists in file system
    pdf.always.generate: True

test:
  '[app:main]':
    cache:
      regions: public.data, session
      type: memory
      public.data.expire: 10
    edware:
      db:
        cat:
          schema_name: edware_sds_0_2
          url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware_functional_tests
    auth:
      skip.verify: False
      saml:
        idp_server_login_url: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso/SSORedirect/metaAlias/idp
        idp_server_logout_url: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso/IDPSloRedirect/metaAlias/idp
        issuer_name: http://localhost:6543/sp.xml
        name_qualifier: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso
    mode: dev

jenkins_dev:
  '[app:main]':
    celery:
      BROKER_URL: amqp://edware:edware1234@localhost//
      CELERY_IMPORTS: ('services.pdf.tasks',)
      CELERY_RESULT_BACKEND: amqp
      CELERYD_CONCURRENCY: 8
    edware:
      db:
        schema_name: edware_sds_0_2
        cat:
          url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware_functional_tests
    auth:
      policy.secure: False
      skip.verify: False
      saml:
        issuer_name: 'http://edwappsrv1.poc.dum.edwdc.net/'
        idp_server_login_url: 'http://edwappsrv4.poc.dum.edwdc.net:18080/opensso/SSORedirect/metaAlias/idp'
        idp_server_logout_url: 'http://edwappsrv4.poc.dum.edwdc.net:18080/opensso/IDPSloRedirect/metaAlias/idp'
        name_qualifier: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso
    mode: test
    cache.public.data.url: edwappsrv1.poc.dum.edwdc.net:11211
    cache.session.url: edwappsrv2.poc.dum.edwdc.net:11211
