###
# app configuration
# http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/environment.html
###

common:
  '[app:main]':
    use: egg:smarter
    disable_stack_trace: false
    smarter.PATH: /usr/local/bin
    batch.user.session.timeout: 300000
    pyramid:
      reload_templates: true
      debug_all: false
      debug_authorization: false
      debug_notfound: false
      debug_routematch: false
      default_locale_name: en
      includes: pyramid_tm pyramid_exclog pyramid_beaker

    # pyramid_beaker configuration
    cache:
      regions: public.data, public.filtered_data, public.shortlived, session
      type: ext:memcached
      expire: 3600 # one hour
      public.data.expire: 31556940 # year
      public.filtered_data.expire: 15552000 # six month
      public.shortlived.expire: 7776000 # three months
      session.expire: 1200 # 20 minutes
      lock_dir: /tmp/memcache

    # Database
    edware:
      db:
        echo: False
    trigger:
      recache:
        enable: False
        filter.file:  /opt/edware/conf/comparing_populations_precache_filters.json
        schedule:
          cron:
            day: '*/1'
      pdf:
        enable: False
        schedule:
          cron:
            day: '*/1'

    # Authentication
    auth:
      state:
        secret: long_secret_for_redirects1111234
      policy:
        secret: edware_secret
        cookie_name: edware
        hashalg: sha512
        http_only: true
        # Represents the lifetime of the cookie itself, if it's not set, it's session based cookie
        #max_age: 2400
        # Maximum number of seconds which a newly issued ticket will be considered valid
        timeout: 1200
        # Session expiration time
      session:
        timeout: 1200
      idp:
        metadata: ../../resource/idp_metadata.xml

    # Static cache max age
    smarter.resources.static.max_age: 3600
    # We support dev, prod, and test (env that runs FT) modes
    mode: dev
    # Run npm update (dev mode only)
    run.npm.update: true
    # Timeout for pdf generation process
    pdf:
      # expected pdf file size in bytes used to validate that pdf was generated without errors
      minimum_file_size: 59000
      # number of retries allowed after the first failure
      retries_allowed: 1
      # delay in retry in seconds
      retry_delay: 0
      generate_timeout: 10
      report_base_dir: /tmp/pdf
      celery_timeout: 30
      # Don't regenerate if pdf is in file system
      always_generate: False
      base.url: http://localhost:6543/assets/html/
      batch.job.queue: batch_pdf_gen
      health_check.job.queue: health_check
    # Used for tenancy
    ldap.base.dn: ou=environment,dc=edwdc,dc=net
    # Use context security
    disable.context.security: True
    extract:
      retry_delay: 60
      retries_allowed: 1
      work_zone_base_dir: /tmp
      gpg.homedir: ~/.gnupg
      gpg.public_key.cat: Kimberly Swimberly
      sftp.route.base_dir: route
      cleanup.schedule.cron.day: last
    sftp.jail.base_path: /sftp
    pickup:
      sftp.hostname: edwappsrv5.poc.dum.edwdc.net
      sftp.user: filerouter
      sftp.private_key_file: /var/lib/jenkins/.ssh/id_rsa
      gatekeeper.cat: kswimberly
      gatekeeper.dog: skong
  '[server:main]':
    use: 'egg:waitress#main'
    host: 0.0.0.0
    port: 6543

  ###
  # logging configuration
  # http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/logging.html
  ###

  '[loggers]':
    keys: root, smarter, sqlalchemy, exc_logger, audit, edauth, security_event

  '[handlers]':
    keys: console, filelog, audit, security_event

  '[formatters]':
    keys: generic, json

  '[logger_edauth]':
    level: DEBUG
    handlers: filelog
    qualname: edauth

  '[logger_root]':
    level: INFO
    handlers: filelog, console

  '[logger_smarter]':
    level: INFO
    handlers: filelog
    qualname: smarter

  '[logger_sqlalchemy]':
    level: WARN
    handlers: filelog
    qualname: sqlalchemy
    # "level = INFO" logs SQL queries.
    # "level = DEBUG" logs SQL queries and results.
    # "level = WARN" logs neither.  (Recommended for production systems.)

  '[logger_exc_logger]':
    level: ERROR
    handlers: filelog
    qualname: exc_logger

  '[logger_audit]':
    level: INFO
    handlers: audit
    qualname: audit
    # Important: this means it doesn't propagate to root logger
    propagate: 0

  '[logger_security_event]':
    level: INFO
    handlers: security_event
    qualname: security_event
    # Important: this means it doesn't propagate to root logger
    propagate: 0

  '[handler_console]':
    class: StreamHandler
    args: (sys.stderr,)
    level: NOTSET
    formatter: generic

  '[handler_filelog]':
    class: logging.handlers.TimedRotatingFileHandler
    args: '(''/tmp/smarter.log'',''midnight'')'  # (path, when)
    level: INFO
    formatter: generic

  '[handler_audit]':
    class: logging.handlers.TimedRotatingFileHandler
    args: '(''/tmp/audit.log'',''midnight'')'   # (path, when)
    level: INFO
    formatter: json

  '[handler_security_event]':
    class: logging.handlers.TimedRotatingFileHandler
    args: '(''/tmp/security_event.log'',''midnight'')'   # (path, when)
    level: INFO
    formatter: json

  '[formatter_generic]':
    format: '%(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s'

  '[formatter_json]':
    class: edapi.logging.JsonDictLoggingFormatter
    format: '%(asctime)s %(message)s'


# End logging configuration

qa:
  '[app:main]':
    mode: prod
    smarter.PATH: /usr/local/bin:/opt/wkhtmltopdf/bin
    services.celery:
      BROKER_URL: amqp://edware:edware1234@rbtmqdw0.qa.dum.edwdc.net//
      CELERY_IMPORTS: ('services.tasks.pdf',)
      CELERY_RESULT_BACKEND: amqp
      CELERY_TASK_RESULT_EXPIRES: 18000 # 5 hours
      CELERYD_CONCURRENCY: 20
    extract.celery:
      BROKER_URL: amqp://edware:edware1234@rbtmqdw0.qa.dum.edwdc.net//
      CELERY_IMPORTS: ('edextract.tasks.extract',)
      CELERY_RESULT_BACKEND: amqp
      CELERY_TASK_RESULT_EXPIRES: 18000 # 5 hours
      CELERYD_CONCURRENCY: 20
    cache:
      public.shortlived.url: twprxydw0.qa.dum.edwdc.net:22121
      public.data.url: twprxydw0.qa.dum.edwdc.net:22121
      session.url: twprxydw0.qa.dum.edwdc.net:22121
      public.filtered_data.url: twprxydw0.qa.dum.edwdc.net:22121
    pdf:
      base.url: https://ha-int-pyweb0.qa.dum.edwdc.net/assets/html/
      report_base_dir: /opt/edware/pdf
      generate_timeout: 30
      health_check.job.queue: health_check
    edware:
      db:
        cat:
          schema_name: edware_es_1_0
          url: postgresql+psycopg2://edware:edware2013@dwpool1.qa.dum.edwdc.net:6432/edware
    edware_stats:
      db:
        schema_name: edware_es_1_0
        url: postgresql+psycopg2://edware:edware2013@dbpgdw0.qa.dum.edwdc.net:5432/edware_stats
    auth:
      idp:
        metadata: /opt/edware/conf/idp_metadata.xml
      policy:
        secure: true
      skip.verify: False
      saml:
        issuer_name: https://ha-int-pyweb0.qa.dum.edwdc.net
        idp_server_login_url: https://auth1.qa.dum.edwdc.net/openam/SSORedirect/metaAlias/idp
        idp_server_logout_url: https://auth1.qa.dum.edwdc.net/openam/IDPSloRedirect/metaAlias/idp
        name_qualifier: https://auth1.qa.dum.edwdc.net/openam
  '[handlers]':
    keys: audit, syslog, security_event
  '[logger_root]':
    level: INFO
    handlers: syslog
  '[handler_syslog]':
    class: logging.handlers.SysLogHandler
    args: '(''/dev/log'', handlers.SysLogHandler.LOG_LOCAL1)'
    level: WARN
    formatter: generic
  '[handler_audit]':
    class: logging.handlers.SysLogHandler
    args: '(''/dev/log'', handlers.SysLogHandler.LOG_LOCAL0)'
    level: WARN
    formatter: json
  '[handler_security_event]':
    class: logging.handlers.SysLogHandler
    args: '(''/dev/log'', handlers.SysLogHandler.LOG_LOCAL2)'
    level: INFO
    formatter: json
  '[logger_smarter]':
    level: WARN
    handlers: syslog
    qualname: smarter
  '[logger_edauth]':
    level: WARN
    handlers: syslog
    qualname: edauth
  '[logger_sqlalchemy]':
    level: WARN
    handlers: syslog
    qualname: sqlalchemy
  '[logger_exc_logger]':
    level: ERROR
    handlers: syslog
    qualname: exc_logger

jenkins_qa:
  '[app:main]':
    mode: test
    edware:
      db:
        cat:
          schema_name: edware_sds_1_2
          url: postgresql+psycopg2://postgres:edware.qa.2013@dwpool0.qa.dum.edwdc.net:6432/edware
    edware_stats:
      db:
        schema_name: edware_sds_1_2
        url: postgresql+psycopg2://edware:edware2013@dwpool0.qa.dum.edwdc.net:6432/edware_stats

uat:
  '[app:main]':
    mode: prod
    smarter.PATH: /usr/local/bin:/opt/wkhtmltopdf/bin
    services.celery:
      BROKER_URL: amqp://edware:edware1234@rbtmqdw0.dmo.som.edwdc.net//
      CELERY_IMPORTS: ('services.tasks.pdf',)
      CELERY_RESULT_BACKEND: amqp
      CELERY_TASK_RESULT_EXPIRES: 18000 # 5 hours
      CELERYD_CONCURRENCY: 20
    extract.celery:
      BROKER_URL: amqp://edware:edware1234@rbtmqdw0.dmo.som.edwdc.net//
      CELERY_IMPORTS: ('edextract.tasks.extract',)
      CELERY_RESULT_BACKEND: amqp
      CELERY_TASK_RESULT_EXPIRES: 18000 # 5 hours
      CELERYD_CONCURRENCY: 20
    cache:
      public.shortlived.url: twprxydw0.dmo.som.edwdc.net:22121
      public.data.url: twprxydw0.dmo.som.edwdc.net:22121
      session.url: twprxydw0.dmo.som.edwdc.net:22121
      public.filtered_data.url: twprxydw0.dmo.som.edwdc.net:22121
    pdf:
      base.url: https://beta.smarterbalancedreporting.org/assets/html/
      report_base_dir: /opt/edware/pdf
      generate_timeout: 30
      health_check.job.queue: health_check
    disable_stack_trace: true
    edware:
      db:
        es:
          schema_name: edware_uat_1_0
          url: postgresql+psycopg2://edware:edware.dmo.may.2013@dwpool0.dmo.som.edwdc.net:6432/edware
    edware_stats:
      db:
        schema_name: edware_uat_1_0
        url: postgresql+psycopg2://edware:edware.dmo.may.2013@dbpgdw0.dmo.som.edwdc.net:5432/edware_stats
    auth:
      idp:
        metadata: /opt/edware/conf/idp_metadata.xml
      policy:
        secure: true
      skip.verify: False
      saml:
        issuer_name: https://pyweb.dmo.som.edwdc.net
        idp_server_login_url: https://betaauth.smarterbalancedreporting.org/openam/SSORedirect/metaAlias/idp
        idp_server_logout_url: https://betaauth.smarterbalancedreporting.org/openam/IDPSloRedirect/metaAlias/idp
        name_qualifier: https://betaauth.smarterbalancedreporting.org/openam
  '[handlers]':
    keys: audit, syslog, security_event
  '[logger_root]':
    level: INFO
    handlers: syslog
  '[handler_syslog]':
    class: logging.handlers.SysLogHandler
    args: '(''/dev/log'', handlers.SysLogHandler.LOG_LOCAL1)'
    level: WARN
    formatter: generic
  '[handler_audit]':
    class: logging.handlers.SysLogHandler
    args: '(''/dev/log'', handlers.SysLogHandler.LOG_LOCAL0)'
    level: WARN
    formatter: json
  '[handler_security_event]':
    class: logging.handlers.SysLogHandler
    args: '(''/dev/log'', handlers.SysLogHandler.LOG_LOCAL2)'
    level: INFO
    formatter: json
  '[logger_smarter]':
    level: WARN
    handlers: syslog
    qualname: smarter
  '[logger_edauth]':
    level: WARN
    handlers: syslog
    qualname: edauth
  '[logger_sqlalchemy]':
    level: WARN
    handlers: syslog
    qualname: sqlalchemy
  '[logger_exc_logger]':
    level: ERROR
    handlers: syslog
    qualname: exc_logger

localOpenAM:
  '[app:main]':
    edware:
      db:
        cat:
          schema_name: edware_sds_1_2
          url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware
          echo: False
    edware_stats:
      db:
        schema_name: edware_sds_1_2
        url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware_stats
    auth:
      skip.verify: False
      saml:
        idp_server_login_url: http://local.slidev.org:8080/openam/SSORedirect/metaAlias/idp
        idp_server_logout_url: http://local.slidev.org:8080/openam/IDPSloRedirect/metaAlias/idp
        issuer_name: http://local.slidev.org:6543/sp.xml
        name_qualifier: http://local.slidev.org:8080/openam
    mode: dev

development:
  '[app:main]':
    cache:
      regions: public.data, public.filtered_data, public.shortlived, session
      type: memory
      public.data.expire: 10
    # Celery config
    services.celery:
      celery_always_eager: true
    extract.celery:
      celery_always_eager: true
    edware:
      db:
        pool_size: 20
        max_overflow: 10
        cat:
          schema_name: edware_sds_1_2
          url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware
        dog:
          schema_name: edware_sds_1_2_dog
          url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware
    edware_stats:
      db:
        schema_name: edware_sds_1_2
        url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware_stats

    auth:
      skip.verify: False
      saml:
        idp_server_login_url: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso/SSORedirect/metaAlias/idp
        idp_server_logout_url: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso/IDPSloRedirect/metaAlias/idp
        issuer_name: http://localhost:6543/sp.xml
        name_qualifier: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso

    # Don't cache any static contents
    smarter.resources.static.max_age: 0
    # Always generate pdf regardless if it exists in file system
    pdf:
      always_generate: True
      health_check.job.queue: health_check
    trigger.recache.filter.file:  ../config/comparing_populations_precache_filters.json
    sftp.jail.base_path: /tmp
      
test:
  '[app:main]':
    cache:
      regions: public.data, public.filtered_data, public.shortlived, session
      type: memory
      public.data.expire: 10
      public.shortlived.expire: 10
    edware:
      db:
        cat:
          schema_name: edware_sds_1_2
          url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware_functional_tests
        dog:
          schema_name: edware_sds_1_2_dog
          url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware_functional_tests
    edware_stats:
      db:
        schema_name: edware_sds_1_2
        url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware_functional_tests_stats
    auth:
      skip.verify: False
      saml:
        idp_server_login_url: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso/SSORedirect/metaAlias/idp
        idp_server_logout_url: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso/IDPSloRedirect/metaAlias/idp
        issuer_name: http://localhost:6543/sp.xml
        name_qualifier: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso
    mode: dev
    trigger.recache.filter.file:  ../config/comparing_populations_precache_filters.json

jenkins_dev:
  '[app:main]':
    services.celery:
      BROKER_URL: amqp://edware:edware1234@localhost/services
      CELERY_IMPORTS: ('services.tasks.pdf',)
      CELERY_RESULT_BACKEND: amqp
      CELERY_TASK_RESULT_EXPIRES: 1800 # 30 min
      CELERYD_CONCURRENCY: 8
    extract:
      celery:
        BROKER_URL: amqp://edware:edware1234@localhost/edextract
        CELERY_IMPORTS: ('edextract.tasks.extract',)
        CELERY_RESULT_BACKEND: amqp
        CELERY_DEFAULT_QUEUE : extract
        CELERY_DEFAULT_ROUTING_KEY: extract
        CELERY_TASK_RESULT_EXPIRES: 18000 # 5 hours
        CELERYD_CONCURRENCY: 8
      gpg.homedir : /var/lib/jenkins/.gnupg
    edware:
      db:
        cat:
          schema_name: edware_sds_1_2
          url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware_functional_tests
        dog:
          schema_name: edware_sds_1_2_dog
          url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware_functional_tests
    edware_stats:
      db:
        schema_name: edware_sds_1_2
        url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware_functional_tests_stats
    auth:
      policy.secure: False
      skip.verify: False
      saml:
        issuer_name: 'http://edwappsrv1.poc.dum.edwdc.net/'
        idp_server_login_url: 'http://edwappsrv4.poc.dum.edwdc.net:18080/opensso/SSORedirect/metaAlias/idp'
        idp_server_logout_url: 'http://edwappsrv4.poc.dum.edwdc.net:18080/opensso/IDPSloRedirect/metaAlias/idp'
        name_qualifier: http://edwappsrv4.poc.dum.edwdc.net:18080/opensso
    mode: test
    pdf:
      report_base_dir: /opt/edware/pdf
      base.url: http://edwappsrv1.poc.dum.edwdc.net/assets/html/
      health_check.job.queue: health_check
    cache:
      public.shortlived.url: edwappsrv1.poc.dum.edwdc.net:11211
      public.filtered_data.url: edwappsrv1.poc.dum.edwdc.net:11211
      public.data.url: edwappsrv1.poc.dum.edwdc.net:11211
      session.url: edwappsrv2.poc.dum.edwdc.net:11211
    pickup:
      sftp.hostname: localhost

air:
  '[app:main]':
    cache:
      regions: public.data, public.filtered_data, public.shortlived, session
      type: memory
      public.data.expire: 10
    # Celery config
    services.celery:
      celery_always_eager: true
    extract.celery:
      celery_always_eager: true
    edware:
      db:
        ca:
          schema_name: edware_sds_1_2
          url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware_functional_tests
        dog:
          schema_name: edware_sds_1_2_dog
          url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware_functional_tests
    edware_stats:
      db:
        schema_name: edware_sds_1_2
        url: postgresql+psycopg2://edware:edware2013@edwdbsrv1.poc.dum.edwdc.net:5432/edware_stats
    auth:
      skip.verify: False
      saml:
        idp_server_login_url: http://sso-dev.opentestsystem.org:8080/auth/SSORedirect/metaAlias/sbac/idp
        idp_server_logout_url: http://sso-dev.opentestsystem.org:8080/auth/IDPSloRedirect/metaAlias/sbac/idp
        issuer_name: http://localhost:6543/sp.xml
        name_qualifier: http://sso-dev.opentestsystem.org:8080/auth
        identity_parser: smarter.security.sbac_identity_parser.SbacIdentityParser
      idp:
        metadata: ../../resource/air_idp_metadata.xml
    # Don't cache any static contents
    smarter.resources.static.max_age: 0
    # Always generate pdf regardless if it exists in file system
    pdf:
      always_generate: True
      health_check.job.queue: health_check
    trigger.recache.filter.file:  ../config/comparing_populations_precache_filters.json
